export const productCopy = {
  brand: {
    name: "Dear Hoomin",
    description: "Daily pet thoughts for hoomins.",
  },
  navigation: {
    admin: "Admin",
    dismiss: "Dismiss",
    home: "Home",
    homeSections: "Home sections",
    primary: "Primary",
    settings: "Settings",
    signOut: "Sign out",
    signedInFallback: "signed-in hoomin",
    tabs: {
      thoughts: "Musings",
      journal: "Journal",
      pet: "Furbaby",
      family: "Family",
    },
  },
  auth: {
    eyebrow: "Dear Hoomin",
    heading: "see today's tiny thought.",
    intro: "Sign in with Google to open your daily pet ritual.",
    googleButton: "Continue with Google",
    errors: {
      fallback: "Login failed.",
      googleTokenExchangeFailed: "Google login did not finish. Try again.",
      googleAuthFailed: "Google login did not finish. Try again.",
      missingAuthCode: "Google did not return a login code. Try again.",
      missingOauthState: "Google login expired. Try again.",
      invalidOauthState: "Google login could not be verified. Try again.",
    },
  },
  home: {
    eyebrow: "Dear Hoomin",
    headings: {
      noFamily: "ready for tiny thoughts?",
      noPet: "who's thinking today?",
    },
    family: {
      intro: "Make a little home first, then your pet can start posting tiny thoughts.",
      nameLabel: "Family name",
      namePlaceholder: "Mochi's household",
      createButton: "Create family",
      creatingButton: "Making family...",
    },
    noPet: {
      intro: "No furbaby here yet. Add one little face before the daily musings can begin.",
      addPetLink: "Add furbaby",
      visual: "?",
    },
    journal: {
      ariaLabel: "Add a journal",
      petLabel: "Pet",
      photosLabel: "Photos",
      noteLabel: "Journal note",
      notePlaceholder: (petName: string) => `what happened with ${petName} today?`,
      submitButton: "Make a journal thought",
      pendingButton: "Making journal...",
    },
    thoughts: {
      listLabel: "Thoughts",
      emptyVisual: "soon",
      drawingTodayPicture: "Drawing today's picture",
      fallbackThought: (petName: string) =>
        `${petName} is still deciding what to tell the hoomin.`,
      inFlightStatus: (petName: string) =>
        `${petName} is thinking real hard. Old thoughts can stay cozy here.`,
      makeMusingButton: "Make today's musing",
      drawingButton: "Drawing...",
      firstDoodleStatus: "A fresh thought will appear after the first doodle.",
      tryDrawingAgainButton: "Try drawing again",
      addMusingLabel: "Add musing",
    },
  },
  media: {
    generatedThoughtAlt: (petName: string) => `${petName}'s generated thought`,
    journalPhotoAlt: (petName: string, index: number) =>
      `${petName} journal photo ${index + 1}`,
    avatarAlt: (petName: string) => `${petName}'s avatar`,
    avatarOptionAlt: (petName: string) => `${petName} avatar option`,
    selectedAvatarAlt: (petName: string) => `${petName} selected avatar`,
    originalUploadAlt: (petName: string) => `${petName} original upload`,
    dailyMusingAlt: (petName: string) => `${petName} daily musing`,
    baseAvatarStyleAlt: "Base avatar style",
    thoughtImageAlt: (petName: string) => `${petName}'s thought`,
  },
  petForm: {
    nameLabel: "Furbaby name",
    namePlaceholder: "Mochi",
    speciesLabel: "Species",
    speciesPlaceholder: "cat, dog...",
    referencePhotoLabel: "Reference photo",
    addButton: "Add furbaby",
    addingButton: "Adding pet...",
  },
  photoPicker: {
    noPhotoSelected: "No photo selected",
    noPhotosSelected: "No photos selected",
    photosSelected: (count: number) => `${count} photos selected`,
    choosePhoto: "Choose photo",
    choosePhotos: "Choose photos",
    acceptedFormats: "JPEG, PNG, WebP, HEIC",
  },
  avatars: {
    heading: (petName: string) => `Which one looks most like ${petName}?`,
    error: "That doodle wandered off. Try again.",
    generating: "Making three tiny faces",
    pickingButton: "Picking...",
    pickedButton: "Picked",
    pickMeButton: "Pick me",
    loadingGridLabel: "Avatar generation loading",
    loadingSlot: (slot: number) => `tiny face ${slot}`,
    needsAvatar: (petName: string) =>
      `We need a tiny avatar before ${petName} can post thoughts.`,
    uploadingButton: "Uploading...",
    doodlingButton: "Doodling...",
    makeNewButton: "Make 3 new avatars",
  },
  share: {
    pictureNotReady: "The share picture is not ready yet.",
    pictureButton: "Share picture",
    preparingPictureButton: "Preparing picture...",
    linkButton: "Copy link",
    copyingButton: "Copying...",
    linkCopied: "Link copied.",
    linkReady: "Link ready to copy.",
    linkCopyFailed: "Link could not be copied here.",
    title: "Dear Hoomin",
    text: (petName: string) => `what's ${petName} thinking?`,
    fileName: (petName: string) => `${petName}-thought.png`,
    generatedPictureLabel: "generated picture",
    journalPhotoLabel: (photoNumber: number) => `journal photo ${photoNumber}`,
    showMediaLabel: (mediaLabel: string) => `Show ${mediaLabel}`,
    previousPictureLabel: "Previous picture",
    nextPictureLabel: "Next picture",
    pictureChoicesLabel: "Picture choices",
    thoughtPicturesLabel: (petName: string) => `${petName} thought pictures`,
  },
  inviteLink: {
    label: "Latest invite link",
    copyButton: "Copy invite link",
    copiedStatus: "Invite link copied.",
    readyStatus: "Link ready to copy.",
  },
  timeline: {
    drawing: "Drawing",
    generationRunning: "Picture generation is still running.",
    generationFailed: "Picture generation failed.",
    generationNotStarted: "Picture generation has not started yet.",
  },
  dates: {
    todayFallback: "today",
  },
  family: {
    eyebrow: "Family",
    memberCount: (count: number) =>
      `${count} hoomin${count === 1 ? "" : "s"} in this family.`,
    familiesLabel: "Families",
    inviteHeading: "Invite hoomins",
    createInviteButton: "Create invite link",
    membersHeading: "Members",
    removeButton: "Remove",
    addPetHeading: "Add furbaby",
    furbabiesHeading: "Furbabies",
    addFurbabyHeading: "Add furbaby",
    todayMusingsHeading: "Today's furbaby musings",
    furbabyNameLabel: "Furbaby name",
    savingButton: "Saving...",
    saveFurbabyButton: "Save furbaby",
    realWorldPhotoLabel: "Real-world photo",
    replacePhotoButton: "Replace photo",
    petsHeading: "Pets",
    musingWaiting: "today's musing is waiting.",
    pictureInFlight: "Picture generation is in flight.",
    pictureFailed: "Picture generation failed. Try again.",
    pictureReady: "Today's picture is ready.",
    noPicture: "No picture generated yet.",
    chooseAvatarLink: "Choose avatar",
    generatePictureButton: "Generate picture",
  },
  invite: {
    eyebrow: "Invite",
    missingHeading: "this invite is missing.",
    missingIntro: "Ask your family hoomin for a fresh invite link.",
    heading: (familyName: string) => `join ${familyName}?`,
    memberCount: (count: number) =>
      `${count} hoomin${count === 1 ? "" : "s"} are already here.`,
    openFamilyLink: "Open family",
    expiredError: "This invite link has expired.",
    joinButton: "Join family",
  },
  settings: {
    eyebrow: "Furbaby",
    fallbackPetName: "little one",
    addPetHeading: "Add your pet",
    pickFaceIntro: "Pick a little face so thoughts have a consistent look.",
    realWorldHeading: (petName: string) =>
      `How ${petName} looks like in real world`,
    uploadRealWorldPhotoLabel: "Upload one real-world photo",
    replaceRealWorldPhotoButton: "Replace real-world photo",
    aboutHeading: (petName: string) => `About ${petName}`,
    fallbackFurbaby: "your furbaby",
    tellUsLabel: (petName: string) => `Tell us a bit more about ${petName}`,
    notesPlaceholder:
      "likes dramatic snack updates, suspicious of laundry, always alert...",
    saveNotesButton: "Save furbaby notes",
    dailyMusingHeading: "Daily musing time",
    dailyMusingIntro:
      "Dear Hoomin makes each daily musing at 6am in this timezone.",
    timezoneLabel: "Timezone",
    saveTimezoneButton: "Save timezone",
    notificationsHeading: "Notifications",
    notificationsIntro: "Want a tiny nudge when your pet posts a thought?",
    allNudgesLabel: "All tiny nudges",
    dailyMusingReadyLabel: "Daily musing ready",
    saveNudgesButton: "Save nudges",
  },
  notifications: {
    unsupported: "This browser cannot do little nudges yet.",
    missingPublicKey: "Notifications are missing their public key.",
    deniedSoft: "No worries. Tiny nudges are off in this browser.",
    ready: "Tiny nudges are ready for this browser.",
    enableFailed: "Could not enable nudges here yet.",
    blocked: "Notifications are blocked in browser settings.",
    refreshButton: "Refresh browser nudges",
    enableButton: "Enable browser nudges",
  },
  homeScreenPrompt: {
    eyebrow: "iPhone app",
    heading: "Add Dear Hoomin to Home Screen",
    steps: [
      {
        title: "Tap Share",
        body: "Use Safari's share button.",
      },
      {
        title: "Add to Home Screen",
        body: "Scroll the sheet if it is lower down.",
      },
      {
        title: "Tap Add",
        body: "Dear Hoomin opens like an app next time.",
      },
    ],
    dismissButton: "Got it",
  },
  admin: {
    eyebrow: "Admin",
    heading: "ops checks.",
    intro: "Run narrow production diagnostics without exposing them to regular hoomins.",
    pushHeading: "Push notifications",
    dailyGenerationHeading: "Daily generation",
    dailyGenerationIntro:
      "Runs the same daily cron logic now, including timezone and 6am checks.",
    baseAvatarStyleHeading: "Base avatar style",
    baseAvatarStyleIntro:
      "This system image guides every pet avatar. Hoomins can tweak content, not the style.",
    noBaseAvatarStyle: "No base avatar style uploaded yet.",
    styleImageLabel: "Style image",
    uploadStyleButton: "Upload style",
    runDailyGenerationButton: "Run daily generation now",
    runningButton: "Running...",
    dailyGenerationResult: (candidateCount: number, dueCount: number, attempted: number) =>
      `Checked ${candidateCount} candidates for their current local dates, found ${dueCount} needing images, attempted ${attempted}.`,
    dailyGenerationError: (error: string) => `Not run: ${error}`,
    pushUnsupportedOrDenied: (permission: "denied" | "unsupported") =>
      `Push notifications are ${
        permission === "denied" ? "blocked" : "not supported"
      } in this browser.`,
    sendTestNotificationButton: "Send test notification",
    enableNotificationsButton: "Enable notifications",
    sendingButton: "Sending...",
    permissionNotGranted: "Permission was not granted.",
    testSent: "Push service accepted the test.",
    testNotSent: (status: string, code?: number | null) =>
      `Not sent: ${status}${code ? ` ${code}` : ""}`,
  },
  serviceWorker: {
    defaultNotificationTitle: "Dear Hoomin",
    defaultNotificationBody: "Push notifications are wired up.",
  },
  push: {
    testTitle: "Dear Hoomin",
    testBody: "Push notifications are wired up.",
    thoughtPublishedTitle: (petName: string) => `${petName} has a tiny thought`,
  },
} as const;
